#+TITLE: \huge Homework 11
#+AUTHOR: MATH 115 @@latex:\\@@ UC Berkeley @@latex:\\@@ Guilherme Gomes Haetinger

#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}

\begin{center}
\line(1,0){250}
\end{center}

* _7.1_

** 1) Expand the rational fractions
*** $\frac{17}{3}$
    \begin{eqnarray*}
      17 =& 3*5 + 2 \\
      3 =& 2*1 + 1 \\
      2 =& 1*2
    \end{eqnarray*}
    \begin{eqnarray*}
      \frac{17}{3} = 5 + \frac{1}{1 + \frac{1}{2}}
    \end{eqnarray*}
*** $\frac{3}{17}$
    \begin{eqnarray*}
      3 =& 17*0 + 3 \\
      17 =& 3 ...
    \end{eqnarray*}
    \begin{eqnarray*}
      \frac{3}{17} = 0 + \frac{1}{\frac{17}{3}} = \frac{1}{5 + \frac{1}{1 + \frac{1}{2}}}
    \end{eqnarray*}
*** $\frac{8}{1}$
    \begin{eqnarray*}
      8 =& 1*8 + 0
    \end{eqnarray*}
    \begin{eqnarray*}
      \frac{8}{1} = 8
    \end{eqnarray*}

** 2) Prove that the set (7.1) consists of exactly one equation if and only if $u_1 = 1$. Under what circumstances is $a_0 = 0$?
   The Euclidean Algorithm set of equation ends when we get to the GCD of the two numbers involved, because then the residue is null. Considering that, for 7.1, we have the GCD equal 1, the set of equations will have exactly one equation when $u_1 = 1$ as well as $u_1 = 1$ when we have a set of equations with only one equation or else the GCD $\not= 1$.
   $a_0 = 0$ when $u_0 < u_1$.

** Convert into rational numbers
*** <2, 1, 4>
    $<2, 1, 4> = 2 + \frac{1}{1 + \frac{1}{4}} = 2 + \frac{1}{\frac{5}{4}} = 2 + \frac{4}{5} = \frac{14}{5}$
    
*** <-3, 2, 12>
    $<-3, 2, 12> = -3 + \frac{1}{2 + \frac{1}{12}} = -3 + \frac{1}{\frac{25}{12}} = -3 + \frac{12}{25} = \frac{-63}{25}$
    
*** <0, 1, 1, 100>
    $<0, 1, 1, 100> = 0 + \frac{1}{1 + \frac{1}{1 + \frac{1}{100}}} = \frac{1}{1 + \frac{1}{\frac{101}{100}}} = \frac{1}{1 + \frac{100}{101}} = \frac{1}{\frac{201}{101}} = \frac{101}{201}$
** 3) Given positive integers /b, c, d/ with /c > d/, prove that /<a, c> < <a, d>/ but /<a, b, c> > > <a, b, d>/ for any integer /a/.
   Considering that $c > d$, when /c/ is on the second position of the rational number representation, we have that it divides the number by a greater magnitude, i.e. $c > d \to \frac{1}{c} < \frac{1}{d} \to a + \frac{1}{c} < a + \frac{1}{d}$.
   We know that the number in the third position's magnitude will contribute to the magnitude of the rational number being represented, in contrast with thee second position's magnitude. This way, $c > d \to \frac{1}{\frac{1}{c}} = c > \frac{1}{\frac{1}{d}} = d$, meaning the representation inequality holds. 
** 4) Let $a_1, a_2 ,...,a_n$ and $c$ be positive real numbers. Prove that $<a_0, a_1, ..., a_n> > <a_0, a_1, ..., a_n + c>$ holds if /n/ is odd, but is false if /n/ is even.
   We can use the same principle as before. When the position of a number is even, we have that its magnitude lowers the overall magnitude of the number because it divides it properly, while if its odd, it actually increases the magnitude because it multiplies it. This way the statement holds, considering that $a_n < a_n + c$.

\begin{center}
\line(1,0){250}
\end{center}

* _7.2_
** 1) Let $a_1, a_2 ,...,a_n$ and $b_1, b_2, ..., b_{n+1}$ be positive integers. State the conditions for $<a_0, a_1, ..., a_n> < <b_0, b_1, ..., b_{n+1}>$.
   Consider an integer /x/ that denotes the smallest /i/ so that $a_i \not= b_i$.

   First, consider $x \le n-1$. Then if $x = 0$, we must have that $a_0 < b_0$. If $x = 1$, we must have that $a_1 > b_1$. It all goes on by the proof in question 7.1#5: if /x/ is even, we need the $a_x < b_x$ so its representation will be of lower magnitude; while if /x/ is odd, we need $a_x > b_x$ for the same reason as before.
   
   Now let's consider $x = n$. We need to take into consideration the parity of /n/. If it's odd, we need $a_n > b_n + \frac{1}{b_{n+1}}$ and, if it's even, we need $a_n < b_n + \frac{1}{b_{n+1}}$.

\begin{center}
\line(1,0){250}
\end{center}

* _7.3_
** 1) Evaluate the infinite continued fraction <1, 1, 1, 1, ... >.
   We know that $x = 1 + \frac{1}{x} \to x² - x - 1 = 0$. This way we calculate the roots for this equation to get the value of /x/ by $x = \frac{1 \pm \sqrt{5}}{2} = \frac{1 + \sqrt{5}}{2}$, which is the only positive one. Now we know the value of the fraction.
** Evaluate the infinite continued fractions <2, 1, 1, 1, 1, ... > and <2, 3, 1, 1, 1, 1, ... >.
   Considering the previous result, we have that, for the first representation, $x_0 = 2 + \frac{2}{1 + \sqrt5}$ and, for the second one, $x_0 = 2 + \frac{1}{x_1}, x_1 = 3 + \frac{2}{1 + \sqrt5}$
** Evaluate the infinite continued fractions
*** <2, 1, 2, 1, ...>
    We follow the same proposal as the last ones. $x_0 = 2 + \frac{1}{x_1}, x_1 = 1 + \frac{1}{x_0} \to x_0 = 2 + \frac{x_0}{x_0 + 1} \to x_0² + x_0 = 3x_0 + 2 \to x_0² - 2x_0 - 2 = 0$. Now we can get the roots: $\frac{2 \pm \sqrt{4 + 8}}{2} = 1 \pm \sqrt3 \to x_0 = 1 + \sqrt3$, which is the only positive root. Then, we can calculate $x_1$ based on that, by doing $x_1 = 1 + \frac{1}{1+\sqrt3} = \frac{2}{1 + \sqrt3}$.
*** <1, 3, 1, 2, 1, 2, 1, ...>
    We can use the previous results to calculate the value from the third position. This way we can say that $x_0 = 1 + \frac{1}{x_1}, x_1 = 3 + \frac{1}{x_3}, x_3 = \frac{2}{1 + \sqrt3}$. Now we can calculate $x_1 = 3 + \frac{1 + \sqrt3}{2} = \frac{7 + \sqrt3}{2} \to x_0 = 1 + \frac{2}{7 + \sqrt3} = \frac{9 + \sqrt3}{7 + \sqrt3}$.
** For $n \ge 1$, prove that $k_n/k_{n-1} = <a_n,a_{n_1},...,a_2,a_1>$. Find and prove a similar continued fraction expansion for $h_n/h_{n-1}$ assuming $a_0 > 0$.
   We have the following cases: $n = 1 \to <a_1> = a_1 = \frac{k_1}{k_0}, <a_2, a_1> = a_2 + \frac{1}{a_1}$. Let $<a_{n-1}, a_{n-2}, ..., a_2, a_1> = \frac{k_{n-1}}{k_{n-2}}$. Now $<a_n, ..., a_1> = a_n + \frac{k_{n-2}}{k_{n-1}}, k_n = a_nk_{n-1} + k_{n-2} \to <a_n, ..., a_1> = \frac{k_n}{k_{n-1}}$
   We have $\frac{h_0}{h_1} = a_0, <a_1, a_0> = a_1 + \frac{1}{a_0}, \frac{h_1}{h_0} = a_1 + \frac{1}{a_0}$. Let $<a_{n-1}, ..., a_1> = \frac{h_{n-1}}{h_{n-2}}$. Then, for $a>0$, by induction, $<a_n, ..., a_1> = \frac{h_n}{h_{n-1}}$.
